import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

export default function MovieItem({info}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cinema Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cinema.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            {info.title}
        </h1>

        <p>Nota: {info.vote_average}</p>

        <p>{info.overview}</p>

        <img src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} width="50%" />
        
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const response = await fetch(`http://localhost:3000/api/movie/${context.params.id}`);
  const json = await response.json();

  return {
    props: {
      info: json.info
    },
  };
}
