import Head from "next/head";
import Link from 'next/link'
import Image from "next/image";
import styles from "../../styles/Home.module.css";

export default function MovieItem({info}) {
  return (
    <div className={styles.containerMovie}>
      <Head>
        <title>{info.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.mainMovie}>
        <h1 className={styles.titleMovie}>
            {info.title}
        </h1>

        {/* <Image src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`}
            alt={`Poster ${item.title}`}       
            width={150} 
            height={500}
        /> */}

        {/*  alt={`Poster ${item.title}`} */}

        <img className={styles.backgroundMovie} src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} />

        <img className={styles.backdrop} src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} />

        <p className={styles.overview}>{info.overview}</p>

        {/* <p>Nota: {info.vote_average}</p> */}
        
      </main>
    </div>
  );
}

// getClientSideProps()

// getClientProps()

// getServerSideProps()

export async function getClientSideProps(context) {
  const response = await fetch(`http://localhost:3000/api/movie/${context.params.id}`);
  const json = await response.json();

  return {
    props: {
      info: json.info
    },
  };
}
