import Head from "next/head";
import Link from 'next/link'
import Image from "next/image";
import styles from "../../styles/Home.module.css";

export default function MovieItem({info}) {
  return (
    <div className={styles.containerMovie}>
      <Head>
        <title>{info.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.mainMovie}>
        <h1 className={styles.titleMovie}>
            {info.title}
        </h1>

        {/* <Image src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`}
            alt={`Poster ${item.title}`}       
            width={150} 
            height={500}
        /> */}

        {/*  alt={`Poster ${item.title}`} */}

        <img className={styles.backgroundMovie} src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} />

        <img className={styles.backdrop} src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} />

        <p className={styles.informationPrimary}>{info.release_date} • {info.genres[0].name} • {info.runtime}m </p> 

        <p className={styles.overview}>{info.overview}</p>

        <p className={styles.information}>Nota: {info.vote_average} • Avaliações: {info.vote_count}</p>


        
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/movie/${context.params.id}`);
  const json = await response.json();

  return {
    props: {
      info: json.info
    },
  };
}

// ENDPOINT com todas informações por filme
// https://api.themoviedb.org/3/movie/587?api_key=2eeeb76c18c8747ca40b9e3b007cd4e4&language=en-US