import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { BiSearchAlt } from "react-icons/bi";
import Image from 'next/image'
import Link from 'next/link'

export default function Busca({ list }) {
  const [searchText, setSearchText] = useState("");
  const [movieList, setMovieList] = useState([]);

  const handleSearch = async () => {
    if (searchText !== "") {
      const result = await fetch(
        `http://localhost:3000/api/search?movie=${searchText}`
      );

      const json = await result.json();
      setMovieList(json.list);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Busca por filmes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <div className={styles.supertitle}>
          <BiSearchAlt /> <h1 className={styles.title}>Buscar</h1>
        </div>
        <input className={styles.input}
          type="text"
          value={searchText}
          onChange={(e) => setSearchText(e.target.value)}
        />
        <button className={styles.button} onClick={handleSearch}>Buscar</button>

        <ul>
          {movieList.map((item, key) => (
            <li key={key}>
              <a href={`/movie/${item.id}`}> <a>
                <img
                  src={`https://image.tmdb.org/t/p/original${item.poster_path}`}
                  width="150px"
                />

              {/* <Image src={`https://image.tmdb.org/t/p/original${item.poster_path}`}
                  alt={`Poster ${item.title}`}
                  width={150} 
                  height={500}
              /> */}

                <br />
                {/* {item.title} */}
                </a>
              </a>
            </li>
          ))}
        </ul>
      </main>
    </div>
  );
}
