import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ list }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cinema Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cinema.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Filmes em Destaque</h1>

        <Link href="/busca">Ir para a Busca</Link>

        <ul>
          {list.map((item) => (
            <li>
              <a href={`/movie/${item.id}`}>
                <img
                  src={`https://image.tmdb.org/t/p/original${item.poster_path}`}
                  width="150px"
                />
                <br />
                {item.title}
              </a>
            </li>
          ))}
        </ul>
      </main>

      <Link href="./sobre">Sobre mim</Link>

    </div>
  );
}

// Exportanto essa função, automaticamente a página irá ser renderizada no server side

export async function getServerSideProps() {
  const response = await fetch("http://localhost:3000/api/trending");
  const json = await response.json();

  return {
    props: {
      list: json.list,
    },
  };
}
