import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sobre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Sobre o Sistema</h1>

        Aplicação desenvolvida para melhorar minhas habilidades em NextJs

        Author: {props.author}

      </main>

    </div>
  );
}

// export async function getStaticProps() {
//   const response = await fetch("http://localhost:3000/api/trending");
//   const json = await response.json();

//   return {
//     props: {
//       author: 'Filipi'
//     },
//   };
// }
